[package]
name = "ethlambda"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
ethlambda-blockchain.workspace = true
ethlambda-p2p.workspace = true
ethlambda-types.workspace = true
ethlambda-rpc.workspace = true
ethlambda-storage.workspace = true

spawned-concurrency.workspace = true
spawned-rt.workspace = true
tokio.workspace = true

tracing.workspace = true
tracing-subscriber = "0.3"

serde.workspace = true
serde_json.workspace = true
serde_yaml_ng = "0.10"
hex.workspace = true

ethereum-types.workspace = true
clap.workspace = true

[build-dependencies]
vergen.workspace = true
vergen-git2.workspace = true
