name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: ["**"]
  workflow_dispatch:

# Cancel in-progress runs when a new commit is pushed to the same PR or branch
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  CARGO_NET_GIT_FETCH_WITH_CLI: "true"
  CARGO_NET_RETRY: "10"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "1.92.0"
          components: rustfmt, clippy

      - name: Setup cache
        uses: Swatinem/rust-cache@v2

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Cargo check
        run: cargo check --workspace --all-targets

      - name: Clippy
        run: cargo clippy --workspace --all-targets -- -D warnings

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      # - name: Download test fixtures
      #   env:
      #     GH_TOKEN: ${{ github.token }}
      #   run: |
      #     mkdir -p leanSpec/fixtures
      #     gh run download --repo leanEthereum/leanSpec --name fixtures-prod-scheme --dir leanSpec/fixtures

      - name: Checkout leanSpec
        uses: actions/checkout@v6
        with:
          repository: leanEthereum/leanSpec
          ref: 050fa4a18881d54d7dc07601fe59e34eb20b9630
          path: leanSpec

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Generate test fixtures
        working-directory: leanSpec
        run: |
          uv sync
          uv run fill --fork=devnet --clean -n auto

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "1.92.0"

      - name: Setup cache
        uses: Swatinem/rust-cache@v2

      - name: Run tests
        run: make test
